#!/bin/bash

#docker run --rm -it -p 5002:443 -e ASPNETCORE_URLS="https://+;" \
#  -e ASPNETCORE_HTTPS_PORTS=5000 -e ASPNETCORE_Kestrel__Certificates__Default__Password="" \
#   -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx -v \
#   ${HOME}/.certs:/https/ dustech-app-web

docker run -it --rm -p 5002:5002 -e ASPNETCORE_HTTP_PORTS=5002 --name dustech-app-web dustech-app-web