#!/bin/bash

docker run --rm -it -p 5001:443 -e ASPNETCORE_URLS="https://+;" \
  -e ASPNETCORE_HTTPS_PORTS=5000 -e ASPNETCORE_Kestrel__Certificates__Default__Password="" \
   -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx -v \
   ${HOME}/.certs:/https/ dustech-idp

# docker run -it --rm -p 5000:5001 --name dustech-idp dustech-idp