version: '3.8'

services:
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${HOME}/certbot/www/:/var/www/certbot/:rw
      - ${HOME}/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - dustech-network
  
  nginx:
    image: dustech-nginx
    ports:
      - "80:80"
      - "443:443"
    #restart: always
    volumes:
      #- ${HOME}/.certs:/etc/nginx/ssl:ro     
      - ${HOME}/certbot/www/:/var/www/certbot/:ro
      - ${HOME}/certbot/conf/:/etc/nginx/ssl/:ro
    networks: 
      - dustech-network    
  
  
  webapp:
    image: dustech-webapp
    expose:
      - "5002" 
#    ports:
#      - "5002:5002"
    environment:
      ASPNETCORE_HTTP_PORTS: "5002" 
      # ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      DataProtectionConfiguration__x509__FileName: ${WebApp_DataProtectionConfiguration__X509__FileName}
      DataProtectionConfiguration__x509__Key: ${WebApp_DataProtectionConfiguration__X509__Key}
      DataProtectionConfiguration__X509__Path: ${WebApp_DataProtectionConfiguration__X509__Path}
      DataProtectionConfiguration__DataProtectionPath: ${WebApp_DataProtectionConfiguration__DataProtectionPath}   
    volumes:
      - ${WebApp_DataProtectionConfiguration__DataProtectionPath}:${WebApp_DataProtectionConfiguration__DataProtectionPath}
      - ${WebApp_DataProtectionConfiguration__X509__Path}:${WebApp_DataProtectionConfiguration__X509__Path}:ro
    networks:
      - dustech-network


  idp:
    image: dustech-idp
    expose:
      - "5001"
#    ports:
#      - "5001:5001"
    environment:
      ASPNETCORE_HTTP_PORTS: "5001"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      DataProtectionConfiguration__x509__FileName: ${Idp_DataProtectionConfiguration__X509__FileName}
      DataProtectionConfiguration__x509__Key: ${Idp_DataProtectionConfiguration__X509__Key}
      DataProtectionConfiguration__X509__Path: ${Idp_DataProtectionConfiguration__X509__Path}
      DataProtectionConfiguration__DataProtectionPath: ${Idp_DataProtectionConfiguration__DataProtectionPath}
    volumes:
      - ${Idp_DataProtectionConfiguration__DataProtectionPath}:${Idp_DataProtectionConfiguration__DataProtectionPath}
      - ${Idp_DataProtectionConfiguration__X509__Path}:${Idp_DataProtectionConfiguration__X509__Path}:ro
    networks:
      - dustech-network


networks:
  dustech-network:
    driver: bridge