using System.Collections.Generic;

namespace Dustech.App.Web.Pages.Farewell;

public static class Cities
{
    internal static IEnumerable<string> ItCities =>
        new List<string>
        {
            "Tokyo, JP",
            "Delhi, IN",
            "Shanghai, CN",
            "São Paulo, BR",
            "Città del Messico, MX",
            "Il Cairo, EG",
            "Mumbai, IN",
            "Pechino, CN",
            "Dacca, BD",
            "Osaka, JP",
            "New York, US",
            "Karachi, PK",
            "Buenos Aires, AR",
            "Chongqing, CN",
            "Istanbul, TR",
            "Kolkata, IN",
            "Manila, PH",
            "Lagos, NG",
            "Rio de Janeiro, BR",
            "Tianjin, CN",
            "Kinshasa, CD",
            "Guangzhou, CN",
            "Los Angeles, US",
            "Mosca, RU",
            "Shenzhen, CN",
            "Lahore, PK",
            "Bangalore, IN",
            "Parigi, FR",
            "Londra, GB",
            "Lima, PE",
            "Chengdu, CN",
            "Johannesburg, ZA",
            "Baghdad, IQ",
            "Toronto, CA",
            "Santiago, CL",
            "Madrid, ES",
            "Yangon, MM",
            "Alessandria, EG",
            "Houston, US",
            "Mumbai, IN",
            "Hangzhou, CN",
            "Quanzhou, CN",
            "Bangkok, TH",
            "Hong Kong, HK",
            "Dhaka, BD",
            "Hyderabad, IN",
            "Wuhan, CN",
            "Pune, IN",
            "Riyadh, SA",
            "Chennai, IN"
        };
    
    internal static IEnumerable<string> EnCities =>
        new List<string>
        {
            "Tokyo, JP",
            "Delhi, IN",
            "Shanghai, CN",
            "São Paulo, BR",
            "Mexico City, MX",
            "Cairo, EG",
            "Mumbai, IN",
            "Beijing, CN",
            "Dhaka, BD",
            "Osaka, JP",
            "New York, US",
            "Karachi, PK",
            "Buenos Aires, AR",
            "Chongqing, CN",
            "Istanbul, TR",
            "Kolkata, IN",
            "Manila, PH",
            "Lagos, NG",
            "Rio de Janeiro, BR",
            "Tianjin, CN",
            "Kinshasa, CD",
            "Guangzhou, CN",
            "Los Angeles, US",
            "Moscow, RU",
            "Shenzhen, CN",
            "Lahore, PK",
            "Bangalore, IN",
            "Paris, FR",
            "London, GB",
            "Lima, PE",
            "Chengdu, CN",
            "Johannesburg, ZA",
            "Baghdad, IQ",
            "Toronto, CA",
            "Santiago, CL",
            "Madrid, ES",
            "Yangon, MM",
            "Alexandria, EG",
            "Houston, US",
            "Mumbai, IN",
            "Hangzhou, CN",
            "Quanzhou, CN",
            "Bangkok, TH",
            "Hong Kong, HK",
            "Dhaka, BD",
            "Hyderabad, IN",
            "Wuhan, CN",
            "Pune, IN",
            "Riyadh, SA",
            "Chennai, IN"
        };
}