using System.Collections.Generic;

namespace Dustech.App.Web.Pages.Farewell;

public static class Hobbies
{
    internal static IEnumerable<string> ItHobbies =>
        new List<string>
        {
            "Lettura",
            "Scrittura",
            "Giardinaggio",
            "Cucina",
            "Pasticceria",
            "Pittura",
            "Disegno",
            "Lavoro a maglia",
            "Cucito",
            "Uncinetto",
            "Trapuntatura",
            "Scrapbooking",
            "Fotografia",
            "Videografia",
            "Osservazione degli uccelli",
            "Escursionismo",
            "Campeggio",
            "Pesca",
            "Caccia",
            "Kayak",
            "Canoa",
            "Vela",
            "Surf",
            "Snowboard",
            "Sci",
            "Pattinaggio sul ghiaccio",
            "Pattinaggio in linea",
            "Skateboarding",
            "Danza",
            "Yoga",
            "Pilates",
            "Corsa",
            "Jogging",
            "Ciclismo",
            "Nuoto",
            "Bodybuilding",
            "Arti marziali",
            "Pugilato",
            "Golf",
            "Tennis",
            "Bowling",
            "Tiro con l'arco",
            "Scacchi",
            "Sudoku",
            "Gioco",
            "Canto",
            "Recitazione",
            "Comicità stand-up",
            "Magia",
            "Collezionismo"
        };
    
    internal static IEnumerable<string> EnHobbies =>
        new List<string>
        {
            "Reading",
            "Writing",
            "Gardening",
            "Cooking",
            "Baking",
            "Painting",
            "Drawing",
            "Knitting",
            "Sewing",
            "Crocheting",
            "Quilting",
            "Scrapbooking",
            "Photography",
            "Videography",
            "Birdwatching",
            "Hiking",
            "Camping",
            "Fishing",
            "Hunting",
            "Kayaking",
            "Canoeing",
            "Sailing",
            "Surfing",
            "Snowboarding",
            "Skiing",
            "Ice Skating",
            "Rollerblading",
            "Skateboarding",
            "Dancing",
            "Yoga",
            "Pilates",
            "Running",
            "Jogging",
            "Cycling",
            "Swimming",
            "Bodybuilding",
            "Martial Arts",
            "Boxing",
            "Golfing",
            "Tennis",
            "Bowling",
            "Archery",
            "Chess",
            "Sudoku",
            "Playing",
            "Singing",
            "Acting",
            "Stand-up comedy",
            "Magic",
            "Collecting"
        };
}