//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dustech.App.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Home_IndexModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Home_IndexModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dustech.App.Web.Resources.Pages.Home.IndexModel", typeof(Pages_Home_IndexModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To The Top.
        /// </summary>
        internal static string BackToTheTop {
            get {
                return ResourceManager.GetString("BackToTheTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me introduce myself.
        /// </summary>
        internal static string LetMeIntroduceMyself {
            get {
                return ResourceManager.GetString("LetMeIntroduceMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More About Me.
        /// </summary>
        internal static string MoreAboutMe {
            get {
                return ResourceManager.GetString("MoreAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am passionate about technology and programming. &lt;br&gt;
        ///I started coding when I was 16 years old and after graduating,
        ///I began working as a web programmer. &lt;br&gt;
        ///I started with &lt;lead class=&quot;text-primary&quot;&gt;PHP&lt;/lead&gt; and &lt;lead class=&quot;text-primary&quot;&gt;Java&lt;/lead&gt;,
        ///but for the last years, I have mainly worked in &lt;lead class=&quot;text-primary&quot;&gt;.NET&lt;/lead&gt; in both Windows and Linux environments. &lt;br&gt;
        ///I work with &lt;lead class=&quot;text-primary&quot;&gt;C#&lt;/lead&gt; object-oriented programming, but in my free time I play with functional pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyResume {
            get {
                return ResourceManager.GetString("MyResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my web space, feel free to explore as you please..
        /// </summary>
        internal static string WelcomeToMyWebSpace {
            get {
                return ResourceManager.GetString("WelcomeToMyWebSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a software architect and backend developer from Turin, Italy.
        /// </summary>
        internal static string WhoAmI {
            get {
                return ResourceManager.GetString("WhoAmI", resourceCulture);
            }
        }
    }
}
