//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dustech.App.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Home_IndexModel_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Home_IndexModel_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dustech.App.Web.Resources.Pages.Home.IndexModel.it", typeof(Pages_Home_IndexModel_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualcosa su di me.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torna Su.
        /// </summary>
        internal static string BackToTheTop {
            get {
                return ResourceManager.GetString("BackToTheTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lascia che mi presenti.
        /// </summary>
        internal static string LetMeIntroduceMyself {
            get {
                return ResourceManager.GetString("LetMeIntroduceMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Mio Proposito.
        /// </summary>
        internal static string MoreAboutMe {
            get {
                return ResourceManager.GetString("MoreAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sono appassionato di tecnologia e programmazione. &lt;br&gt;
        ///Ho iniziato a programmare quando avevo 16 anni e dopo la laurea, ho iniziato a lavorare come programmatore web. &lt;br&gt;
        ///Ho iniziato con &lt;lead class=&quot;text-primary&quot;&gt;PHP&lt;/lead&gt; e &lt;lead class=&quot;text-primary&quot;&gt;Java&lt;/lead&gt;, ma negli ultimi anni ho lavorato principalmente con &lt;lead class=&quot;text-primary&quot;&gt;.NET&lt;/lead&gt; sia in ambienti Windows che Linux. &lt;br&gt;
        ///Lavoro con la programmazione orientata agli oggetti &lt;lead class=&quot;text-primary&quot;&gt;C#&lt;/lead&gt;, ma nel mio tempo libero [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyResume {
            get {
                return ResourceManager.GetString("MyResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto su.
        /// </summary>
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto nel mio spazio web, sentiti libero di esplorare come desideri..
        /// </summary>
        internal static string WelcomeToMyWebSpace {
            get {
                return ResourceManager.GetString("WelcomeToMyWebSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sono un architetto software e sviluppatore backend di Torino, Italia.
        /// </summary>
        internal static string WhoAmI {
            get {
                return ResourceManager.GetString("WhoAmI", resourceCulture);
            }
        }
    }
}
